pool:
  vmImage: 'vs2017-win2016'

variables:
  BuildConfiguration: release

steps:
- task: DotNetCoreCLI@1
  displayName: Restore
  inputs:
    command: restore
    projects: |
     src/PartsUnlimited.Models/PartsUnlimited.Models.csproj
     src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj
     test/PartsUnlimited.UnitTests/PartsUnlimited.UnitTests.csproj

- task: DotNetCoreCLI@1
  displayName: Build
  inputs:
    projects: |
     src/PartsUnlimited.Models/PartsUnlimited.Models.csproj
     src/PartsUnlimitedWebsite/PartsUnlimitedWebsite.csproj
     test/PartsUnlimited.UnitTests/PartsUnlimited.UnitTests.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@1
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@1
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'